wells: &id001
- B3
- E3
- B7
conditions_dict:
  SH:
  - B3
  RASA2:
  - E3
  CUL5:
  - B7
emission_feature_names:
- velocity
- area
- circularity
- nuclei_neighbors_30px
- nuclei_neighbors_50px
- nearest_nucleus_dist
- t_cell_neighbors_20px
model_features: []
nuclei_neighbor_radii:
- 30
- 50
t_cell_radius_px: 20
nearest_dist_cap_px: 600
use_dino: true
dino_model_id: facebook/dinov2-base
dino_model_path: /gladstone/engelhardt/home/jadjasu/.cache/huggingface/hub/models--facebook--dinov2-base
dino_patch_px: 50
dino_rgb_alpha: 0.3
dino_batch_size: 256
n_dino_pcs: 10
dino_pca_whiten: true
num_states: 2
num_lags: 0
min_t: 10
init_method: kmeans
init_stickiness: 0.9
num_em_iters: 50
em_seed: 0
allow_divisions: false
ar_warmup: false
standardize_nondino: true
snakemake_runs_dir: /gladstone/engelhardt/lab/MarsonLabIncucyteData/SnakemakeRuns
analysis_run: Finetuned_Analysis_250t_600xy
caliban_run: Caliban_600xy
registration_run: Registration
raw_video_shape:
- 450
- 1040
- 1408
- 2
video_center_extract:
- 600
- 600
frame_start: 50
frame_end: 300
rfp_channel: 0
phase_channel: 1
treehmm_dir: /gladstone/engelhardt/lab/jadjasu/LiveCellUmbrella/treeHMM
output_base_dir: /gladstone/engelhardt/lab/jadjasu/LiveCellUmbrella/treeHMM/analysis/marson_nuclei_dino_k2_50px_lag0
video_fps: 10
video_figsize:
- 6
- 6
video_wells: *id001
video_label_ids: false
sam3_run: Finetuned_Arrietty_Crops_250t_150xy
cell_typing_run: Finetuned_CellTyping_250t_600xy
imaging_pipeline_dir: /gladstone/engelhardt/lab/jadjasu/LiveCellUmbrella/MarsonImagingPipeline
